import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import { env } from "../config/env.js";

const pdfDir = path.resolve("storage", "pdfs");

export function sanitizeFilename(value) {
  return value.replace(/[^a-z0-9-_]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase();
}

function ensurePdfDir() {
  fs.mkdirSync(pdfDir, { recursive: true });
}

function writePdf(filename, render) {
  ensurePdfDir();
  const safeName = `${sanitizeFilename(filename)}.pdf`;
  const filePath = path.join(pdfDir, safeName);
  const doc = new PDFDocument({ margin: 48 });
  doc.pipe(fs.createWriteStream(filePath));
  render(doc);
  doc.end();
  return `${env.pdfBaseUrl}/${safeName}`;
}

export function createInvoicePdf(invoice, customer) {
  return writePdf(`invoice-${invoice._id}`, (doc) => {
    doc.fontSize(22).text("NxtBiz Invoice");
    doc.moveDown();
    doc.fontSize(12).text(`Invoice ID: ${invoice._id}`);
    doc.text(`Customer: ${customer?.name ?? "Unknown customer"}`);
    doc.text(`Due date: ${invoice.dueDate ? new Date(invoice.dueDate).toDateString() : "Not set"}`);
    doc.text(`Amount due: $${Number(invoice.amount ?? 0).toFixed(2)}`);
    doc.moveDown();
    doc.text("Generated by NxtBiz business operations automation.");
  });
}

export function createReportPdf(report) {
  return writePdf(`report-${report._id}`, (doc) => {
    doc.fontSize(22).text(report.title ?? "NxtBiz Report");
    doc.moveDown();
    doc.fontSize(12).text(report.summary ?? "No summary provided.");
    doc.moveDown().text("Metrics");
    Object.entries(report.metrics ?? {}).forEach(([key, value]) => doc.text(`${key}: ${value}`));
    doc.moveDown().text("Recommendations");
    (report.recommendations ?? []).forEach((item) => doc.text(`- ${item}`));
  });
}
